import type { CotacaoDetalhes } from "@/types";

export function emptyCotacaoDetalhes(): CotacaoDetalhes {
  return {
    servicosDesejados: [],
    origem: "",
    destinoForm: "",
    destinosTrechos: [""],
    dataIda: "",
    dataVolta: "",
    flexibilidadeIda: "",
    flexibilidadeVolta: "",
    flexibilidadeIdaOutro: "",
    flexibilidadeVoltaOutro: "",
    horarioSaidaIda: "",
    horarioSaidaVolta: "",
    preferenciaVooIda: "",
    preferenciaVooVolta: "",
    adultos: 1,
    criancas: 0,
    idadesCriancas: "",
    bebes: 0,
    malasDespachadas: false,
    qtdMalas: "",
    bagagemEspecial: false,
    categoriaHospedagem: "",
    comodidadesHospedagem: [],
    qtdQuartos: 1,
    celular: "",
    whatsapp: "",
    whatsappIgualCelular: false,
    preferenciaComunicacao: "",
    usaMilhas: false,
    formaPagamento: "",
    formaPagamentoOutro: "",
    cupomCodigo: "",
    cupomValidoAte: undefined,
  };
}
