"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { useAuth } from "@/contexts/auth-context";
import { useData } from "@/contexts/data-context";
import type { LancamentoCategoria } from "@/types";

const currency = (raw: string) => (Number(raw.replace(/\D/g, "")) / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const number = (raw: string) => Number(raw.replace(/\./g, "").replace(",", "."));

export default function CadastroDespesaPage() {
  const { addLancamento } = useData();
  const { token } = useAuth();
  const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [category, setCategory] = useState<LancamentoCategoria>("operacional"); const [recurrence, setRecurrence] = useState(""); const [account, setAccount] = useState(""); const [notes, setNotes] = useState(""); const [attachment, setAttachment] = useState<File | null>(null); const [attempted, setAttempted] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const invalid = { description: attempted && !description.trim(), amount: attempted && number(amount) <= 0, date: attempted && !date };
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); setAttempted(true); const value = number(amount); if (!description.trim() || value <= 0 || !date) { setError("Preencha os campos obrigatórios destacados."); return; } setSaving(true); try { const created = await addLancamento({ descricao: description.trim(), tipo: "saida", categoria: category, valor: value, data: date, status: "confirmado", contaBancaria: account.trim() || undefined, recorrencia: recurrence ? recurrence as "MONTHLY" | "WEEKLY" | "YEARLY" : undefined, observacoes: notes.trim() || undefined }); if (attachment) { const base = process.env.NEXT_PUBLIC_AGENCIA_HUB_API_URL; if (!base || !token) throw new Error("Não foi possível enviar o anexo sem conexão com a API."); const form = new FormData(); form.append("file", attachment); const upload = await fetch(`${base}/attachments/financial-entries/${created.id}`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); if (!upload.ok) throw new Error("A despesa foi registrada, mas o anexo não pôde ser enviado."); } setDescription(""); setAmount(""); setAccount(""); setRecurrence(""); setNotes(""); setAttachment(null); setAttempted(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível registrar a despesa."); } finally { setSaving(false); } }
  return <div className="space-y-6"><div><Link href="/financeiro" className="text-sm text-[var(--hub-blue)] hover:underline">← Financeiro</Link><h1 className="mt-2 text-2xl font-bold text-[var(--hub-text-primary)]">Cadastrar despesa</h1><p className="text-sm text-[var(--hub-text-secondary)]">Registre somente um pagamento que saiu da conta da agência.</p></div><form onSubmit={submit} className="grid gap-4 rounded-xl border border-[var(--hub-border)] bg-white p-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Descrição *</Label><Input className={invalid.description ? "border-red-500" : ""} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Ex.: pagamento de fornecedor" /></div><div><Label>Valor pago *</Label><Input className={invalid.amount ? "border-red-500" : ""} value={amount} onChange={(event) => setAmount(currency(event.target.value))} inputMode="numeric" placeholder="0,00" /></div><div><Label>Data do pagamento *</Label><Input className={invalid.date ? "border-red-500" : ""} type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div><Label>Categoria *</Label><Select value={category} onChange={(event) => setCategory(event.target.value as LancamentoCategoria)}><option value="operacional">Operacional</option><option value="passagem">Passagem</option><option value="hospedagem">Hospedagem</option><option value="comissao">Comissão</option><option value="marketing">Marketing</option><option value="outros">Outros</option></Select></div><div><Label>Recorrência</Label><Select value={recurrence} onChange={(event) => setRecurrence(event.target.value)}><option value="">Despesa única</option><option value="MONTHLY">Mensal</option><option value="WEEKLY">Semanal</option><option value="YEARLY">Anual</option></Select></div><div><Label>Conta de onde saiu</Label><Input value={account} onChange={(event) => setAccount(event.target.value)} placeholder="Ex.: Conta PJ" /></div><div className="sm:col-span-2"><Label>Anexo (opcional)</Label><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,text/csv" onChange={(event) => { const file = event.target.files?.[0] ?? null; if (file && file.size > 5 * 1024 * 1024) { setError("O anexo deve ter até 5 MB."); event.target.value = ""; return; } setAttachment(file); }} /><p className="mt-1 text-xs text-[var(--hub-text-muted)]">Imagem, PDF ou texto — até 5 MB.</p></div><div className="sm:col-span-2"><Label>Observações</Label><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} className="w-full rounded-[var(--hub-radius)] border border-[var(--hub-border)] px-3 py-2 text-sm" placeholder="Detalhes do pagamento" /></div>{error && <p role="alert" className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="sm:col-span-2"><Button type="submit" disabled={saving}>{saving ? "Salvando..." : "Registrar despesa"}</Button></div></form></div>;
}
